name:                cswk-gloss
version:             0.1.0.0
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2022 Alex Dixon"

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-juicy
- OpenGL
- GLUT

executables:
  lab-getting-started:
    main: Main.hs
    source-dirs:     
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
